urls.py
from django.urls import path, include, reverse_lazy # new
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


from . import views

app_name = 'pixkal2'
urlpatterns = [
    path('', views.mostrarIndex, name='index'),
    path('markerAR/<avatar_id>/', views.MarkerAR, name='markerar'),
    path('soloAR/<avatar_id>/', views.SoloAR, name='soloar'),
    path('treasure/<busquedalugar_id>/', views.IniciarBusqueda, name='treasure'),
    path('treasure/activarBusqueda/<busqueda_id>/', views.ActivarBusqueda, name='activatetreasure'),
    path('treasure/cancelarBusqueda/<busqueda_id>/', views.CancelarBusqueda, name='canceltreasure'),
    path('treasure/iniciar/<busqueda_id>/', views.ComenzarBusqueda, name='starttreasure'),
    path('treasure/status/<busqueda_id>/<busqueda_lugar_id>', views.StatusBusqueda, name='statustreasure'),
    path('accounts/password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('pixkal2:password_reset_done')), name='password_reset'),
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('pixkal2:password_reset_complete')), name='password_reset_confirm'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.Signup, name='signup'),
    path('registrar/busqueda/', views.RegistrarBusqueda, name='registrarbusqueda'),
    path('busqueda/<int:pk>/editar/', views.EditarBusqueda, name='editarbusqueda'),
    path('busqueda/imagen/actualizar/<int:pk>/', views.ActualizarImagenBusqueda, name='actualizarimagenbusqueda'),
    path('registrar/busquedalugar/<busqueda_id>/', views.RegistrarBusquedaLugar, name='registrarbusquedalugar'),
    path('busquedalugar/<int:pk>/editar/', views.EditarBusquedaLugar, name='editarbusquedalugar'),
    path('dashboard/', views.VerDashboard, name='dashboard'),
    path('misbusquedas/', views.VerMisBusquedas, name='misbusquedas'),
    path('mapa/<busqueda_lugar_id>/', views.VerMapa, name='mapa'),
    path('verAvatar/<busqueda_lugar_id>/', views.VerAvatar, name='verAvatar'),
    path('seleccionarAvatar/<avatar_id>/<busqueda_lugar_id>/', views.SeleccionarAvatar, name='seleccionarAvatar'),
    path('galeriaar/', views.VerGaleriaAR, name='galeriaar'),
    path('perfil/actualizar/', views.ActualizarPerfil, name='actualizarperfil'),
    path('pregunta/actualizar/<blugar>/', views.ActualizarPregunta, name='actualizarpregunta'),
    path('pregunta/eliminar/<blugar>/', views.EliminarPregunta, name='eliminarpregunta'),
    path('pregunta/ver/<blugar>/', views.VerPregunta, name='verpregunta'),
    path('sonido/lugar/<blugar>/<tipo>/', views.AgregarSonido, name='agregarsonido'),
    path('sonido/subir/<blugar>/<tipo>/', views.SubirSonido, name='subirsonido'),
    path('sonido/eliminar/<blugar>/<tipo>/', views.EliminarSonido, name='eliminarsonido'),
    path('modelobAR/<blugar>/<tipo>/', views.ModeloBAR, name='modelobar'),
    path('misclases/', views.VerMisClases, name='misclases'),
    path('clase/registrar/', views.RegistrarClase, name='registrarclase'),
    path('clase/editar/<int:pk>/', views.EditarClase, name='editarclase'),
    path('clase/activar/<clase_id>/', views.ActivarClase, name='activarclase'),
    path('clase/cancelar/<clase_id>/', views.CancelarClase, name='cancelarclase'),
    path('clase/visualizar/<clase_id>/<orden>/', views.VisualizarClase, name='visualizarclase'),
    path('clase/imagen/actualizar/<int:pk>/', views.ActualizarImagenClase, name='actualizarimagenclase'),
    path('item/registrar/<clase_id>/', views.RegistrarItemClase, name='registraritemclase'),
    path('item/actualizar/<item_id>/', views.ActualizarClaseItem, name='actualizaritemclase'),
    path('clase/item/avatar/actualizar/<int:pk>/', views.ActualizarItemImagenClase, name='actualizaritemimagenclase'),
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError

# Create your models here.

def upload_location(instance, filename):
    filebase, extension = filename.split('.')
    return 'images/%s.%s' % (instance.usuario.id, extension)

# Ubicación de imagenes en búsqueda
def upload_location_busqueda(instance, filename):
    filebase, extension = filename.split('.')
    return 'images/b%s.%s' % (instance.id, extension)

# Ubicación de imagenes en clase
def upload_location_clase(instance, filename):
    filebase, extension = filename.split('.')
    return 'images/c%s.%s' % (instance.id, extension)

# Ubicación de sonidos en búsqueda
def upload_location_treasure_s(instance, filename):
    filebase, extension = filename.split('.')
    return 'sonidos/s%s.%s' % (instance.id, extension)

# Ubicación de sonidos clase
def upload_location_c(instance, filename):
    filebase, extension = filename.split('.')
    return 'sonidos/c%s.%s' % (instance.id, extension)

# Ubicación de avatares (clase item)
def upload_location_a(instance, filename):
    filebase, extension = filename.split('.')
    return 'avatares/%s.%s' % (instance.id, extension)

def validate_image(image):
    file_size = image.file.size
    limit_kb = 10500
    if file_size > limit_kb * 1024:
        raise ValidationError("Tamaño máximo del archivo %s KB" % limit_kb)

class Avatar(models.Model):
    tipo = models.CharField(max_length=200, default='GPS')
    titulo = models.CharField(max_length=100, default="Avatar")
    model_3DName = models.CharField(max_length=200)
    model_Image = models.CharField(max_length=200)
    def __str__(self):
        return self.model_3DName

class Perfil(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ForeignKey(Avatar, on_delete=models.CASCADE)
    imagen_busqueda = models.ImageField(upload_to=upload_location, validators=[validate_image])

class Busqueda(models.Model):
    OPCIONES_ESTADO = (
        ('I', 'Inactivo'),
        ('C', 'Cancelado'),
        ('A', 'Activo'),
        ('T', 'Terminado'),
    )

    titulo_busqueda = models.CharField(max_length=350)
    recompensa = models.CharField(max_length=200)
    creacion = models.DateTimeField(auto_now=True)
    ultima_modificacion = models.DateTimeField(auto_now_add=True)
    descripcion = models.TextField(max_length=350, default="")
    numero_personas = models.PositiveSmallIntegerField()
    estado = models.CharField(max_length=1, choices=OPCIONES_ESTADO)
    creador = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    no_items = models.PositiveSmallIntegerField(default=0)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, default=1)
    imagen = models.ImageField(upload_to=upload_location_busqueda, default="", validators=[validate_image])
    contador_visitas = models.IntegerField(default=0)
    contador_usuarios = models.IntegerField(default=0)
    def __str__(self):
        return self.titulo_busqueda

class BusquedaLugar(models.Model):
    busqueda = models.ForeignKey(Busqueda, on_delete=models.CASCADE)
    avatar = models.ForeignKey(Avatar, on_delete=models.CASCADE)
    latitud = models.DecimalField(max_digits=9, decimal_places=6)
    longitud = models.DecimalField(max_digits=9, decimal_places=6)
    pregunta = models.TextField(max_length=350, default="")
    respuesta = models.CharField(max_length=20, default="")
    bandera_pregunta = models.SmallIntegerField(default=0)
    sonido = models.FileField(upload_to=upload_location_treasure_s, default="", validators=[validate_image])
    bandera_sonido = models.SmallIntegerField(default=0)
    creacion = models.DateTimeField(auto_now=True)
    ultima_modificacion = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.busqueda.titulo_busqueda

class BusquedaParticipante(models.Model):
    OPCIONES_ESTADO = (
        ('P', 'Pendiente'),
        ('A', 'Activo'),
        ('G', 'Ganador'),
        ('T', 'Terminado'),
    )
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    busqueda = models.ForeignKey(Busqueda, on_delete=models.CASCADE)
    items_encontrados = models.SmallIntegerField()
    estado = models.CharField(max_length=1, choices=OPCIONES_ESTADO)
    creacion = models.DateTimeField(auto_now=True)
    ultima_modificacion = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.busqueda.titulo_busqueda

class ItemEncontrado(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    busqueda = models.ForeignKey(Busqueda, on_delete=models.CASCADE)
    lugar = models.ForeignKey(BusquedaLugar, on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.busqueda.titulo_busqueda

class Clase(models.Model):
    OPCIONES_ESTADO = (
        ('I', 'Inactivo'),
        ('C', 'Cancelado'),
        ('A', 'Activo'),
        ('T', 'Terminado'),
    )

    OPCIONES_MARCADOR = (
        ('M', 'Utilizar marcador'),
        ('S', 'Sin marcador'),
    )

    OPCIONES_CAMARA = (
        ('L', 'Libre'),
        ('F', 'Mirar de frente'),
    )

    titulo = models.CharField(max_length=350)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ForeignKey(Avatar, on_delete=models.CASCADE)
    creacion = models.DateTimeField(auto_now=True)
    descripcion = models.TextField(max_length=350, default="")
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, default=1)
    imagen = models.ImageField(upload_to=upload_location_clase, default="", validators=[validate_image])
    no_items = models.PositiveSmallIntegerField(default=0)
    bandera_marcador = models.CharField(max_length=1, choices=OPCIONES_MARCADOR, default="M")
    estado = models.CharField(max_length=1, choices=OPCIONES_ESTADO,default="I")
    contador_visitas = models.IntegerField(default=0)
    contador_usuarios = models.IntegerField(default=0)
    bandera_foco = models.CharField(max_length=1, choices=OPCIONES_CAMARA, default="L")
    def __str__(self):
        return self.titulo

class ClaseItem(models.Model):

    OPCIONES_TIPO = (
        ('A', 'Avatar'),
        ('V', 'Video'),
        ('I', 'Imagen'),
    )

    clase = models.ForeignKey(Clase, on_delete=models.CASCADE)
    avatar = models.ForeignKey(Avatar, on_delete=models.CASCADE)
    sonido = models.FileField(upload_to=upload_location_c, default="", validators=[validate_image])
    bandera_sonido = models.SmallIntegerField(default=0)
    creacion = models.DateTimeField(auto_now=True)
    ultima_modificacion = models.DateTimeField(auto_now_add=True)
    bandera_avatar = models.SmallIntegerField(default=0)
    item = models.FileField(upload_to=upload_location_a, default="", validators=[validate_image])
    tipo = models.CharField(max_length=1, choices=OPCIONES_TIPO, default="A")
    def __str__(self):
        return self.clase.titulo

class Dash(models.Model):
    OPCIONES_SERVICIO = (
        ('B', 'Búsqueda'),
        ('C', 'Clase'),
        ('S', 'Stream'),
    )

    OPCIONES_ESTADO = (
        ('I', 'Inactivo'),
        ('C', 'Cancelado'),
        ('A', 'Activo'),
        ('T', 'Terminado'),
    )

    servicio = models.CharField(max_length=1, choices=OPCIONES_SERVICIO, default="M")
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=350)
    descripcion = models.TextField(max_length=350, default="")
    imagen = models.CharField(max_length=350)
    url = models.CharField(max_length=350)
    id_actividad = models.IntegerField(default=0)
    estado = models.CharField(max_length=1, choices=OPCIONES_ESTADO, default='A')
    def __str__(self):
        return self.titulo

templates/pixkal2/activatetreasure.html
{% extends 'pixkal2/base.html' %}

{% block content %}
Búsqueda activada
{% endblock %}

templates/pixkal2/actualizarimagenbusqueda.html
{% extends 'pixkal2/base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'pixkal2/centrar.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
 <form class="form-signin" method="post" enctype="multipart/form-data">
  {% csrf_token %}
<p><label for="id_imagen">Imagen:</label>
<input type="file" name="imagen" accept="image/*" class="form-control" required id="id_imagen"></p>
<button class="btn btn-lg btn-primary btn-block" type="submit">Actualizar</button>
</form>

{% endblock %}

templates/pixkal2/actualizaritemimagenclase.html
{% extends 'pixkal2/base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'pixkal2/centrar.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
 <form class="form-signin" method="post" enctype="multipart/form-data">
  {% csrf_token %}
<p><label for="id_item">Imagen:</label>
<input type="file" name="item" class="form-control" required id="id_item"></p>
<p><label for="id_tipo">Tipo de archivo:</label>
<select name="tipo" id="id_tipo">
  <option value="A" selected>Avatar</option>
  <option value="V">Video</option>
  <option value="I">Imágen</option>
</select></p>
<button class="btn btn-lg btn-primary btn-block" type="submit">Subir</button>
</form>

{% endblock %}

templates/pixkal2/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'pixkal2/bootstrap.min.css' %}" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'pixkal2/centrar.css' %}" rel="stylesheet">

    <style>
    .m_item{
    color: rgba(255,255,255,.5);
    line-height: 1.6;
    display: block;
    padding: .5rem 1rem;
    }
    .m_item:hover{
    color: rgba(255,255,255,.8);
    text-decoration: none;
    }
    </style>

    {% block head %}{% endblock %}

    <title>{% block title %}Pixkal{% endblock %}</title>

  </head>
  <body>
{% if user.is_authenticated %}
    <nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'pixkal2:dashboard' %}"><img src="{% static 'pixkal2/images/Pixkal_Icon.png' %}"></img></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'pixkal2:actualizarperfil' %}">{{user.username}}<span class="sr-only">(current)</span></a>
      </li>

    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Búsqueda
        </a>

    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
        <a class="m_item" href="{% url 'pixkal2:registrarbusqueda' %}">Registrar búsqueda</a>
        <a class="m_item" href="{% url 'pixkal2:misbusquedas' %}">Búsquedas creadas por mí </a>
    </div>

    </li>


    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Clase
        </a>
    <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
        <a class="m_item" href="{% url 'pixkal2:registrarclase' %}">Crear clase </a>
        <a class="m_item" href="{% url 'pixkal2:misclases' %}">Clases creadas por mí </a>
    </div>
    </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'pixkal2:logout' %}">Salir</a>
      </li>
    </ul>
  </div>
</nav>
{% else %}
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'pixkal2:index' %}">Pixkal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExample01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'pixkal2:signup' %}">Registrarse</a>
      </li>
    </ul>
  </div>
</nav>
{% endif %}
    <main role="main" class="container">
{% if user.is_authenticated %}
    <div class="container-fluid">
    <div style="height:20px; padding-bottom: 50px;"></div>
    <div class="row d-flex justify-content-center">
    {% block content %}
    {% endblock %}
    </div>
    </div>

{% else %}

<div class="container-fluid">
<row>
<a class="nav-link" href="{% url 'pixkal2:login' %}">Inicia sesión</a>
</row>
</div>
{% endif %}
 </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

</html>

templates/pixkal2/canceltreasure.html
{% extends 'pixkal2/base.html' %}

{% block content %}
Búsqueda cancelada
{% endblock %}

templates/pixkal2/dashboard.html
{% extends 'pixkal2/base.html' %}

{% load static %}

{% block head %}
<link href="{% static 'pixkal2/cards.css' %}" rel="stylesheet">
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
{% endblock %}

{% block content %}

{% if user.is_authenticated %}

{% if dashboard %}


 <div class="card-columns">
  {% for item in dashboard %}


  <div class="card">
  <div class="wrapper">

<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      {% if item.imagen == "" %}
      <img src="{% static 'pixkal2/images/banner.jpg' %}" class="card-img" alt="...">
      {% else %}
      <img src="/media/{{ item.imagen }}/" class="card-img" alt="...">
      {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{ item.titulo }}</h5>
        <p class="card-text">{{ item.descripcion }}</p>
        <p class="card-text"><small class="text-muted"><a href="/{{ item.url }}">Entrar</a></small></p>
      </div>
    </div>
  </div>
</div>

  </div>


</div>
{% endfor %}
 </div>

  {% if dashboard.has_other_pages %}
  <ul class="pagination">
    {% if dashboard.has_previous %}
      <li class="page-item"><a href="?page={{ dashboard.previous_page_number }}"  class="page-link">&laquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span  class="page-link">&laquo;</span></li>
    {% endif %}
    {% for i in dashboard.paginator.page_range %}
      {% if dashboard.number == i %}
        <li class="active page-item"><span>{{ i }} <span class="sr-only"  class="page-link">(current)</span></span></li>
      {% else %}
        <li class="page-item"><a href="?page={{ i }}"  class="page-link">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if dashboard.has_next %}
      <li class="page-item"><a href="?page={{ dashboard.next_page_number }}"  class="page-link">&raquo;</a></li>
    {% else %}
      <li class="disabled page-item"><span  class="page-link">&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}

{% else %}
<img src="{% static 'pixkal2/images/not_found.png'%}" class="img-fluid" style="max-width: 100%; height: auto;"/>
{% endif %}


{% else %}
Acceso restringido
{% endif %}

<script>

$(document).ready(function($) {

	$('.card__share > a').on('click', function(e){
		e.preventDefault() // prevent default action - hash doesn't appear in url
   		$(this).parent().find( 'div' ).toggleClass( 'card__social--active' );
		$(this).toggleClass('share-expanded');
    });

});


</script>
{% endblock %}

templates/pixkal2/gestionarpregunta.html
{% extends 'pixkal2/base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'pixkal2/centrar.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
 <form class="form-signin" method="post">
  {% csrf_token %}
  <p><label for="pregunta">Reto:</label>
  <textarea name="pregunta" cols="40" rows="10" maxlength="350" class="form-control" required id="id_pregunta">{% if actualizar == 1 %}{{ busquedalugar.pregunta }}{% endif %}
  </textarea></p>
  <p><label for="respuesta">Código:</label>
  <input type="text" name="respuesta" {% if actualizar == 1 %} value="{{ busquedalugar.respuesta }}" {% else %} value="" {% endif %}
   maxlength="350" class="form-control" required id="id_respuesta">
  </p>
{% if actualizar == 1 %}
  <button class="btn btn-lg btn-primary btn-block" type="submit">Actualizar pregunta</button>
{% else %}
  <button class="btn btn-lg btn-primary btn-block" type="submit">Agregar pregunta</button>
{% endif %}
</form>

<div>
    <a href="/pregunta/eliminar/{{ busquedalugar.id }}/">Eliminar</a>
</div>

{% endblock %}

templates/pixkal2/index3.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'pixkal2/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
        <li><a href="{% url 'pixkal2:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

templates/pixkal2/soloAR.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Pixkal</title>
    <script src="https://aframe.io/releases/1.0.4/aframe.min.js"></script>
    <script src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"></script>
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/donmccurdy/aframe-extras@v6.1.0/dist/aframe-extras.min.js"></script>
 </head>

  <!-- we import arjs version without NFT but with marker + location based support -->

  <body style="margin : 0px; overflow: hidden;">
    <a-scene embedded arjs>
      <a-entity
          position="0 2 -5"
          scale="0.2 0.2 0.2"
          gltf-model="/static/pixkal2/gltf/{{ avatar.model_3DName }}" animation-mixer look-at="[camera]">
        </a-entity>
    </a-scene>
  </body>
</html>

templates/pixkal2/starttreasure.html
{% extends 'pixkal2/base.html' %}

{% block content %}
{% if user.is_authenticated %}

{% if busqueda.estado != 'T' %}

<div style="width:100px; position:absolute; height: 30px;"></div>

<a href="/mapa/{{siguientelugar.id}}/" class="btn btn-success" role="button" style="margin-top: 25px;">Iniciar búsqueda</a>
</br></br>
{% endif %}

{% else %}
Acceso restringido
{% endif %}

{% endblock %}

templates/pixkal2/verpregunta.html
{% extends 'pixkal2/base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'pixkal2/centrar.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

{% if error == 1 %}
<div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: 100%;">
    El código no es correcto, ¡Vuelve a intentarlo!
  <button type="button" class="close" data-dismiss="alert" aria-label="Cerrar">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
{% endif %}

 <form class="form-signin" method="post">
  {% csrf_token %}
  <div style="width: 300px;">
      <p>
          {{ busquedalugar.pregunta }}
      </p>
  </div>
  <p><label for="respuesta">Código:</label>
  <input type="text" name="respuesta" value="" maxlength="350" class="form-control" required id="id_respuesta">
  </p>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Responder</button>
</form>
{% endblock %}